apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/canary-weight: '20'
spec:
  rules:
  - host: myapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-no-autoscale
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-with-autoscale
            port:
              number: 80